name: TOML and MITRE Validation

on:
  push:
  workflow_dispatch:

jobs:
  toml-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          python development/Validation.py
      - name: Run MITRE Script
        run: python -u development/mitre.py
          
